spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: eureka-server

server:
  port: 19090

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:19090/eureka/
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME}